name: Get and cache dependecies
description: Get dependencies and cache them 
inputs: # definicja inputu podobnie jak w normalnym workflow
  caching:
    description: Enable/disable caching
    required: false
    default: 'true'
runs: 
  using: 'composite'
  steps:
  - name: Cache dependencies
    if: inputs.caching == 'true' # dostęp przez kontekst inputs
    uses: actions/cache@v4
    with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
  - name: Install dependencies
    run: npm ci
    shell: bash
